export const LANGUAGES = [
  'English',
  'Arabic',
  'Hindi',
  'Bahasa Indonesia',
  'Mandarin',
  'Swahili',
  'Portuguese',
  'Spanish',
  'French',
  'Farsi',
  'Bengali',
  'Urdu',
  'Turkish',
  'Cantonese',
  'Marathi',
  'Tamil',
  'Kurdish',
  'Telugu',
  'Shanghainese',
  'Aramaic',
  'Hokkien',
  'Javanese',
  'Hausa',
  'Sudanese',
  'Pashto',
  'Dari',
  'Punjabi',
] as const

export type Language = typeof LANGUAGES[number]

type SocialLinks = { facebook: string; instagram: string; tiktok: string; twitter: string; telegram: string; youtube: string }

const LANGUAGE_SOCIALS: Partial<Record<Language, SocialLinks>> = {
  'English': {
    facebook: 'https://www.facebook.com/abnsat',
    instagram: 'https://www.instagram.com/abnsat.english/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat.english?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/ABNEnglishTelegram',
    youtube: 'https://www.youtube.com/@AbnEnglish',
  },
  'Arabic': {
    facebook: 'https://www.facebook.com/abnsat',
    instagram: 'https://www.instagram.com/abnsat.arabic/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat?lang=en',
    twitter: 'https://x.com/abnsat',
    telegram: 'https://t.me/ABNArabicTelegram',
    youtube: 'https://www.youtube.com/@ABNArabic',
  },
  'Hindi': {
    facebook: 'https://www.facebook.com/AbnIndiaTV',
    instagram: 'https://www.instagram.com/abnsat.india/',
    tiktok: 'https://www.tiktok.com/@abn.india?lang=en',
    twitter: 'https://x.com/ABNTVIndia1',
    telegram: 'https://t.me/ABNIndiaTelegram',
    youtube: 'https://www.youtube.com/@abnindiatv',
  },
  'Bahasa Indonesia': {
    facebook: 'https://www.facebook.com/profile.php?id=61588926329052',
    instagram: 'https://www.instagram.com/abnsat.indonesia/',
    tiktok: 'https://www.tiktok.com/@abnsat.indonesia?lang=en',
    twitter: 'https://x.com/AbnsatIndonesia',
    telegram: 'https://t.me/AbnsatIndonesia',
    youtube: 'https://www.youtube.com/@ABNSATINDONESIA',
  },
  'Mandarin': {
    facebook: 'https://www.facebook.com/profile.php?id=61581744413770',
    instagram: 'https://www.instagram.com/abnsat.mandarine/',
    tiktok: 'https://www.tiktok.com/@abnsat.mandarine?lang=en',
    twitter: 'https://x.com/abnsatmandarin',
    telegram: 'https://t.me/AbnsatMandarin',
    youtube: 'https://www.youtube.com/@AbnsatChinaMandarine',
  },
  'Swahili': {
    facebook: 'https://www.facebook.com/profile.php?id=61581623850423',
    instagram: 'https://www.instagram.com/abnsat.swahili/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat.swahili?lang=en',
    twitter: 'https://x.com/AbnsatSwahili',
    telegram: 'https://t.me/+_r0SE4LDg0UzMzVh',
    youtube: 'https://www.youtube.com/@AbnsatAfricaSwahili',
  },
  'Portuguese': {
    facebook: 'https://www.facebook.com/profile.php?id=61581293026944',
    instagram: 'https://www.instagram.com/abnsat.portuguese/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat.portuguese?lang=en',
    twitter: 'https://x.com/abnportuguese',
    telegram: 'https://t.me/AbnsatPortuguese',
    youtube: 'https://www.youtube.com/@AbnsatPortuguess',
  },
  'Spanish': {
    facebook: 'https://www.facebook.com/profile.php?id=61581551523787',
    instagram: 'https://www.instagram.com/abnsat.spanish/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat.spanish?lang=en',
    twitter: 'https://x.com/AbnSpanish',
    telegram: 'https://t.me/AbnsatSpanish',
    youtube: 'https://www.youtube.com/@AbnsatSpanish',
  },
  'French': {
    facebook: 'https://www.facebook.com/profile.php?id=61581638129286',
    instagram: 'https://www.instagram.com/abnsat.french/',
    tiktok: 'https://www.tiktok.com/@abnsat.french?lang=en',
    twitter: 'https://x.com/AbnFrench',
    telegram: 'https://t.me/AbnsatFrench',
    youtube: 'https://www.youtube.com/@AbnsatFrench',
  },
  'Farsi': {
    facebook: 'https://www.facebook.com/AbnsatPars',
    instagram: 'https://www.instagram.com/abn.pars/',
    tiktok: 'https://www.tiktok.com/@abnpars',
    twitter: 'https://x.com/AbnPars',
    telegram: 'https://t.me/ABNParsTelegram',
    youtube: 'https://www.youtube.com/@abnIranpars',
  },
  'Bengali': {
    facebook: 'https://www.facebook.com/profile.php?id=61581740698394',
    instagram: 'https://www.instagram.com/abnsat.bengali/',
    tiktok: 'https://www.tiktok.com/@abnsat.bengali?lang=en',
    twitter: 'https://x.com/AbnsatBengali',
    telegram: 'https://t.me/AbnsatBengali',
    youtube: 'https://www.youtube.com/@abnBengali',
  },
  'Urdu': {
    facebook: 'https://www.facebook.com/AbnsatUrdu',
    instagram: 'https://www.instagram.com/abnsat.urdu/',
    tiktok: 'https://www.tiktok.com/@abnsat.urdu?lang=en',
    twitter: 'https://x.com/AbnsatUrdu',
    telegram: 'https://t.me/AbnsatUrdu',
    youtube: 'https://www.youtube.com/@AbnsatPakistanUrdu',
  },
  'Turkish': {
    facebook: 'https://www.facebook.com/AbnsatTurkey',
    instagram: 'https://www.instagram.com/abnsat.turkey/?hl=en',
    tiktok: 'https://www.tiktok.com/@abnsat.turkey?lang=en',
    twitter: 'https://x.com/AbnsatTurkey',
    telegram: 'https://t.me/AbnsatTurkeyTelegram',
    youtube: 'https://www.youtube.com/@AbnsatTurkey',
  },
  'Cantonese': {
    facebook: 'https://www.facebook.com/profile.php?id=61581278717729',
    instagram: 'https://www.instagram.com/abnsat.cantoness/',
    tiktok: 'https://www.tiktok.com/@abnsat.cantonese?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatCantonese',
    youtube: 'https://www.youtube.com/@AbnsatChinaCantonese',
  },
  'Marathi': {
    facebook: 'https://www.facebook.com/profile.php?id=61581852968142',
    instagram: 'https://www.instagram.com/abnsat.marathi/',
    tiktok: 'https://www.tiktok.com/@abnsat.marathi?lang=en',
    twitter: 'https://x.com/AbnsatMarathi',
    telegram: 'https://t.me/AbnsatMarathi',
    youtube: 'https://www.youtube.com/@AbnsatIndiaMarathi',
  },
  'Tamil': {
    facebook: 'https://www.facebook.com/profile.php?id=61581761842937',
    instagram: 'https://www.instagram.com/abnsat.tamil/',
    tiktok: 'https://www.tiktok.com/@abnsat.tamil?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatTamil',
    youtube: 'https://www.youtube.com/@AbnsatIndiaTamil',
  },
  'Kurdish': {
    facebook: 'https://www.facebook.com/AbnsatKurdish',
    instagram: 'https://www.instagram.com/abnsat.kurdish/',
    tiktok: 'https://www.tiktok.com/@abnsat.kurdish?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatKurdish',
    youtube: 'https://www.youtube.com/@AbnsatKurdish',
  },
  'Telugu': {
    facebook: 'https://www.facebook.com/profile.php?id=61581689756567',
    instagram: 'https://www.instagram.com/abnsat.telugu/',
    tiktok: 'https://www.tiktok.com/@abnsat.telugu1',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatTelugu',
    youtube: 'https://www.youtube.com/@AbnsatIndiaTelugu',
  },
  'Shanghainese': {
    facebook: 'https://www.facebook.com/profile.php?id=61589116090946',
    instagram: 'https://www.instagram.com/abnsatshanghainese/',
    tiktok: 'https://www.tiktok.com/@abnsatshanghainese?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/abnsatshanghainese',
    youtube: 'https://www.youtube.com/@AbnsatChinaShanghainese',
  },
  'Aramaic': {
    facebook: 'https://www.facebook.com/AbnsatAramaic',
    instagram: 'https://www.instagram.com/abnsat.aramaic/',
    tiktok: 'https://www.tiktok.com/@abnsat.aramaic',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatAramaic',
    youtube: 'https://www.youtube.com/@aramaicgospel',
  },
  'Hokkien': {
    facebook: 'https://www.facebook.com/profile.php?id=61589394209078',
    instagram: 'https://www.instagram.com/abnsat.hokkien/',
    tiktok: 'https://www.tiktok.com/@abnsathokkien?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/AbnsatHokkien',
    youtube: 'https://www.youtube.com/@AbnsatChinaHokkien',
  },
  'Javanese': {
    facebook: 'https://www.facebook.com/profile.php?id=61589306222842',
    instagram: 'https://www.instagram.com/abnsatjavanese/',
    tiktok: 'https://www.tiktok.com/@abnsat.english?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/abnsatjavanese',
    youtube: 'https://www.youtube.com/@AbnsatIndonesiaJavanese',
  },
  'Hausa': {
    facebook: 'https://www.facebook.com/profile.php?id=61581434473959',
    instagram: 'https://www.instagram.com/abnsat.hausa/',
    tiktok: 'https://www.tiktok.com/@abnsat.english?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/+tCqoQCNYJJk1Nzhh',
    youtube: 'https://www.youtube.com/@AbnsatAfricaHausa',
  },
  'Sudanese': {
    facebook: 'https://www.facebook.com/profile.php?id=61589371381914',
    instagram: 'https://www.instagram.com/abnsatsundanese',
    tiktok: 'https://www.tiktok.com/@abnsat.english?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/Abnsatsundanese',
    youtube: 'https://www.youtube.com/@AbnsatIndonesiaSundanese',
  },
  'Pashto': {
    facebook: 'https://www.facebook.com/profile.php?id=61581767452730',
    instagram: 'https://www.instagram.com/abnsat.pashto/',
    tiktok: 'https://www.tiktok.com/@abnsat.pashto1',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/+oygkHbY0XRQ5MGJh',
    youtube: 'https://www.youtube.com/@ABNSATPASHTO1',
  },
  'Dari': {
    facebook: 'https://www.facebook.com/profile.php?id=61581697675980',
    instagram: 'https://www.instagram.com/abnsat.dari/',
    tiktok: 'https://www.tiktok.com/@abnsat.dari1',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/+6dWlJSw3rYw3NzUx',
    youtube: 'https://www.youtube.com/@abnafghani',
  },
  'Punjabi': {
    facebook: 'https://www.facebook.com/profile.php?id=100068207246843',
    instagram: 'https://www.instagram.com/abnsat.punjabi/',
    tiktok: 'https://www.tiktok.com/@abnsat.english?lang=en',
    twitter: 'https://x.com/TrinityTVLive',
    telegram: 'https://t.me/+3aMMWaArcV0xZWIx',
    youtube: 'https://www.youtube.com/@AbnEnglish',
  },
}

const DEFAULT_SOCIALS: SocialLinks = {
  facebook: 'https://bassimygorialabn12.wixstudio.com/abnfacebook',
  instagram: 'https://bassimygorialabn12.wixstudio.com/abninstagram',
  tiktok: 'https://bassimygorialabn12.wixstudio.com/abntiktok',
  twitter: 'https://bassimygorialabn12.wixstudio.com/abntwitter',
  telegram: 'https://bassimygorialabn12.wixstudio.com/abntelegram',
  youtube: 'https://bassimygorialabn12.wixstudio.com/abnyoutube2',
}

export function getSocials(lang: string | null): Array<{ label: string; href: string }> {
  const s = (lang ? LANGUAGE_SOCIALS[lang as Language] : null) ?? DEFAULT_SOCIALS
  return [
    { label: 'Facebook', href: s.facebook },
    { label: 'Instagram', href: s.instagram },
    { label: 'TikTok', href: s.tiktok },
    { label: 'Twitter / X', href: s.twitter },
    { label: 'Telegram', href: s.telegram },
    { label: 'YouTube', href: s.youtube },
  ]
}
